import {MigrationInterface} from "typeorm";
import {QueryRunner} from "typeorm/query-runner/QueryRunner";

export class SeedCurrencyFixedRates1689677064000 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<any> {
        const currencies = [
            {currency: "eur", fixedRate: 1},
            {currency: "amd", fixedRate: 500},
            {currency: "aud", fixedRate: 1},
            {currency: "bdt", fixedRate: 100},
            {currency: "bif", fixedRate: 2500},
            {currency: "brl", fixedRate: 5},
            {currency: "cad", fixedRate: 1},
            {currency: "cdf", fixedRate: 2500},
            {currency: "chf", fixedRate: 1},
            {currency: "clp", fixedRate: 1000},
            {currency: "cop", fixedRate: 5000},
            {currency: "czk", fixedRate: 25},
            {currency: "dog", fixedRate: 10},
            {currency: "doge", fixedRate: 10},
            {currency: "idr", fixedRate: 10000},
            {currency: "jpy", fixedRate: 100},
            {currency: "kidr", fixedRate: 10},
            {currency: "krw", fixedRate: 1000},
            {currency: "kvnd", fixedRate: 25},
            {currency: "kzt", fixedRate: 500},
            {currency: "mdl", fixedRate: 25},
            {currency: "midr", fixedRate: 10},
            {currency: "mkd", fixedRate: 50},
            {currency: "mmk", fixedRate: 2500},
            {currency: "mvnd", fixedRate: 25},
            {currency: "mvr", fixedRate: 10},
            {currency: "mxn", fixedRate: 25},
            {currency: "myr", fixedRate: 5},
            {currency: "mzn", fixedRate: 75},
            {currency: "nok", fixedRate: 10},
            {currency: "pen", fixedRate: 5},
            {currency: "php", fixedRate: 50},
            {currency: "pkr", fixedRate: 250},
            {currency: "pln", fixedRate: 5},
            {currency: "ron", fixedRate: 5},
            {currency: "sek", fixedRate: 10},
            {currency: "sgd", fixedRate: 1},
            {currency: "thb", fixedRate: 50},
            {currency: "try", fixedRate: 25},
            {currency: "twd", fixedRate: 25},
            {currency: "uah", fixedRate: 50},
            {currency: "usd", fixedRate: 1},
            {currency: "usdc", fixedRate: 1},
            {currency: "usdt", fixedRate: 1},
            {currency: "vnd", fixedRate: 25000},
            {currency: "xaf", fixedRate: 750},
            {currency: "xof", fixedRate: 750},
            {currency: "zar", fixedRate: 25},
            {currency: "aed", fixedRate: 5},
            {currency: "afn", fixedRate: 100},
            {currency: "all", fixedRate: 100},
            {currency: "ars", fixedRate: 250},
            {currency: "bnd", fixedRate: 1},
            {currency: "hkd", fixedRate: 10},
            {currency: "bwp", fixedRate: 10},
            {currency: "crc", fixedRate: 500},
            {currency: "cup", fixedRate: 1},
            {currency: "dop", fixedRate: 50},
            {currency: "dzd", fixedRate: 100},
            {currency: "egp", fixedRate: 25},
            {currency: "etb", fixedRate: 50},
            {currency: "hrk", fixedRate: 7},
            {currency: "gbp", fixedRate: 1},
            {currency: "ghs", fixedRate: 10},
            {currency: "gmd", fixedRate: 75},
            {currency: "gnf", fixedRate: 10000},
            {currency: "hnl", fixedRate: 25},
            {currency: "htg", fixedRate: 100},
            {currency: "ils", fixedRate: 5},
            {currency: "inr", fixedRate: 100},
            {currency: "iqd", fixedRate: 1000},
            {currency: "irr", fixedRate: 50000},
            {currency: "isk", fixedRate: 100},
            {currency: "jmd", fixedRate: 100},
            {currency: "kes", fixedRate: 100},
            {currency: "kgs", fixedRate: 100},
            {currency: "khr", fixedRate: 5000},
            {currency: "lak", fixedRate: 25000},
            {currency: "lbp", fixedRate: 10000},
            {currency: "lkr", fixedRate: 250},
            {currency: "lrd", fixedRate: 250},
            {currency: "lsl", fixedRate: 25},
            {currency: "mad", fixedRate: 10},
            {currency: "ubtc", fixedRate: 25},
            {currency: "xcd", fixedRate: 2},
            {currency: "mga", fixedRate: 5000},
            {currency: "mnt", fixedRate: 5000},
            {currency: "mop", fixedRate: 10},
            {currency: "mur", fixedRate: 50},
            {currency: "mwk", fixedRate: 1000},
            {currency: "nad", fixedRate: 25},
            {currency: "nio", fixedRate: 50},
            {currency: "npr", fixedRate: 100},
            {currency: "xrp", fixedRate: 1},
            {currency: "pab", fixedRate: 1},
            {currency: "pyg", fixedRate: 7500},
            {currency: "qar", fixedRate: 5},
            {currency: "rsd", fixedRate: 100},
            {currency: "rub", fixedRate: 100},
            {currency: "rwf", fixedRate: 1000},
            {currency: "sar", fixedRate: 5},
            {currency: "scr", fixedRate: 10},
            {currency: "srd", fixedRate: 50},
            {currency: "szl", fixedRate: 25},
            {currency: "tjs", fixedRate: 10},
            {currency: "tmt", fixedRate: 5},
            {currency: "trx", fixedRate: 10},
            {currency: "tzs", fixedRate: 2500},
            // {currency: "ueth", fixedRate: 500},
            {currency: "ugx", fixedRate: 5000},
            {currency: "uyu", fixedRate: 50},
            {currency: "uzs", fixedRate: 10000},
            {currency: "ves", fixedRate: 25},
            {currency: "yer", fixedRate: 250},
            {currency: "zmw", fixedRate: 25},
            {currency: "ada", fixedRate: 2},
            {currency: "ang", fixedRate: 2},
            {currency: "aoa", fixedRate: 1000},
            {currency: "azn", fixedRate: 2},
            {currency: "bam", fixedRate: 2},
            {currency: "bch", fixedRate: 1},
            {currency: "bgn", fixedRate: 2},
            {currency: "bhd", fixedRate: 1},
            {currency: "bnb", fixedRate: 1},
            {currency: "mbnb", fixedRate: 5},
            {currency: "bob", fixedRate: 7},
            // {currency: "btc", fixedRate: 1},
            {currency: "byn", fixedRate: 2},
            {currency: "bzd", fixedRate: 2},
            {currency: "cny", fixedRate: 7},
            {currency: "dkk", fixedRate: 7},
            // {currency: "eth", fixedRate: 1},
            {currency: "gel", fixedRate: 2},
            {currency: "gtq", fixedRate: 7},
            {currency: "huf", fixedRate: 250},
            {currency: "jod", fixedRate: 1},
            {currency: "kwd", fixedRate: 1},
            // {currency: "ltc", fixedRate: 1},
            {currency: "mltc", fixedRate: 20},
            // {currency: "mbtc", fixedRate: 1},
            {currency: "meth", fixedRate: 1},
            {currency: "ngn", fixedRate: 750},
            {currency: "nzd", fixedRate: 2},
            {currency: "omr", fixedRate: 1},
            {currency: "ppc", fixedRate: 2},
            {currency: "sdg", fixedRate: 750},
            {currency: "tnd", fixedRate: 2},
            {currency: "ton", fixedRate: 1},
            {currency: "ttd", fixedRate: 7},
            {currency: "lyd", fixedRate: 5},
        ];

        await queryRunner.manager.query(`TRUNCATE rgs_currency`);
        for (const {currency, fixedRate} of currencies) {
            await queryRunner.manager.query(
                `INSERT INTO rgs_currency (currency, "fixedRate")
                 VALUES ('${currency}', ${fixedRate})`,
            );
        }
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.manager.query(`TRUNCATE rgs_currency`);
    }
}
