export const timezones = [
    {label: "UTC", value: "UTC"},
    // Europe
    {label: "Europe/London (GMT/BST)", value: "Europe/London"},
    {label: "Europe/Dublin (GMT/IST)", value: "Europe/Dublin"},
    {label: "Europe/Lisbon (WET/WEST)", value: "Europe/Lisbon"},
    {label: "Europe/Paris (CET/CEST)", value: "Europe/Paris"},
    {label: "Europe/Berlin (CET/CEST)", value: "Europe/Berlin"},
    {label: "Europe/Amsterdam (CET/CEST)", value: "Europe/Amsterdam"},
    {label: "Europe/Brussels (CET/CEST)", value: "Europe/Brussels"},
    {label: "Europe/Madrid (CET/CEST)", value: "Europe/Madrid"},
    {label: "Europe/Rome (CET/CEST)", value: "Europe/Rome"},
    {label: "Europe/Vienna (CET/CEST)", value: "Europe/Vienna"},
    {label: "Europe/Warsaw (CET/CEST)", value: "Europe/Warsaw"},
    {label: "Europe/Prague (CET/CEST)", value: "Europe/Prague"},
    {label: "Europe/Stockholm (CET/CEST)", value: "Europe/Stockholm"},
    {label: "Europe/Oslo (CET/CEST)", value: "Europe/Oslo"},
    {label: "Europe/Copenhagen (CET/CEST)", value: "Europe/Copenhagen"},
    {label: "Europe/Helsinki (EET/EEST)", value: "Europe/Helsinki"},
    {label: "Europe/Athens (EET/EEST)", value: "Europe/Athens"},
    {label: "Europe/Bucharest (EET/EEST)", value: "Europe/Bucharest"},
    {label: "Europe/Sofia (EET/EEST)", value: "Europe/Sofia"},
    {label: "Europe/Kyiv (EET/EEST)", value: "Europe/Kyiv"},
    {label: "Europe/Moscow (MSK)", value: "Europe/Moscow"},
    {label: "Europe/Istanbul (TRT)", value: "Europe/Istanbul"},
    {label: "Europe/Malta (CET/CEST)", value: "Europe/Malta"},
    {label: "Europe/Gibraltar (CET/CEST)", value: "Europe/Gibraltar"},
    // Americas
    {label: "America/New_York (EST/EDT)", value: "America/New_York"},
    {label: "America/Chicago (CST/CDT)", value: "America/Chicago"},
    {label: "America/Denver (MST/MDT)", value: "America/Denver"},
    {label: "America/Phoenix (MST)", value: "America/Phoenix"},
    {label: "America/Los_Angeles (PST/PDT)", value: "America/Los_Angeles"},
    {label: "America/Anchorage (AKST/AKDT)", value: "America/Anchorage"},
    {label: "America/Toronto (EST/EDT)", value: "America/Toronto"},
    {label: "America/Vancouver (PST/PDT)", value: "America/Vancouver"},
    {label: "America/Mexico_City (CST/CDT)", value: "America/Mexico_City"},
    {label: "America/Bogota (COT)", value: "America/Bogota"},
    {label: "America/Lima (PET)", value: "America/Lima"},
    {label: "America/Santiago (CLT/CLST)", value: "America/Santiago"},
    {label: "America/Buenos_Aires (ART)", value: "America/Argentina/Buenos_Aires"},
    {label: "America/Sao_Paulo (BRT)", value: "America/Sao_Paulo"},
    {label: "Pacific/Honolulu (HST)", value: "Pacific/Honolulu"},
    // Asia
    {label: "Asia/Dubai (GST)", value: "Asia/Dubai"},
    {label: "Asia/Riyadh (AST)", value: "Asia/Riyadh"},
    {label: "Asia/Tehran (IRST)", value: "Asia/Tehran"},
    {label: "Asia/Karachi (PKT)", value: "Asia/Karachi"},
    {label: "Asia/Kolkata (IST)", value: "Asia/Kolkata"},
    {label: "Asia/Dhaka (BST)", value: "Asia/Dhaka"},
    {label: "Asia/Bangkok (ICT)", value: "Asia/Bangkok"},
    {label: "Asia/Ho_Chi_Minh (ICT)", value: "Asia/Ho_Chi_Minh"},
    {label: "Asia/Jakarta (WIB)", value: "Asia/Jakarta"},
    {label: "Asia/Singapore (SGT)", value: "Asia/Singapore"},
    {label: "Asia/Kuala_Lumpur (MYT)", value: "Asia/Kuala_Lumpur"},
    {label: "Asia/Manila (PHT)", value: "Asia/Manila"},
    {label: "Asia/Hong_Kong (HKT)", value: "Asia/Hong_Kong"},
    {label: "Asia/Shanghai (CST)", value: "Asia/Shanghai"},
    {label: "Asia/Taipei (CST)", value: "Asia/Taipei"},
    {label: "Asia/Seoul (KST)", value: "Asia/Seoul"},
    {label: "Asia/Tokyo (JST)", value: "Asia/Tokyo"},
    // Oceania
    {label: "Australia/Perth (AWST)", value: "Australia/Perth"},
    {label: "Australia/Adelaide (ACST/ACDT)", value: "Australia/Adelaide"},
    {label: "Australia/Brisbane (AEST)", value: "Australia/Brisbane"},
    {label: "Australia/Sydney (AEST/AEDT)", value: "Australia/Sydney"},
    {label: "Australia/Melbourne (AEST/AEDT)", value: "Australia/Melbourne"},
    {label: "Pacific/Auckland (NZST/NZDT)", value: "Pacific/Auckland"},
    // Africa
    {label: "Africa/Cairo (EET)", value: "Africa/Cairo"},
    {label: "Africa/Johannesburg (SAST)", value: "Africa/Johannesburg"},
    {label: "Africa/Lagos (WAT)", value: "Africa/Lagos"},
    {label: "Africa/Nairobi (EAT)", value: "Africa/Nairobi"},
];
