import {describe, test} from "@jest/globals";
import {createProvablyFairRng} from "../random/createProvablyFairRng";

jest.mock("@slotify/shared/lib/mail", () => ({sendMail: jest.fn, initMail: jest.fn}));
jest.mock("../verify", () => ({verify: jest.requireActual("../verify").verify, setPeriodicVerification: jest.fn}));
jest.mock("../cycle", () => ({cycle: jest.requireActual("../cycle").cycle, setBackgroundCycling: jest.fn}));
jest.mock("../seed", () => ({seed: jest.requireActual("../seed").seed, setPeriodicReseeding: jest.fn}));

describe("provably fair rng", () => {
    test("deterministic output", () => {
        const rngState = {
            serverSeed: "server seed",
            clientSeed: "client seed",
            nonce: 0,
            cursor: 0,
        };

        const number1 = createProvablyFairRng(rngState).random(100);
        const number2 = createProvablyFairRng(rngState).random(100);

        expect(number1).toEqual(number2);
    });

    test("cursor generates new integer outcomes", () => {
        const rngState = {
            serverSeed: "server seed",
            clientSeed: "client seed",
            nonce: 0,
            cursor: 0,
        };

        const rng = createProvablyFairRng(rngState);

        const results = new Set<number>();
        for (let i = 0; i < 1000; i++) {
            const number = rng.random();

            expect(Number.isInteger(number) && number >= 0 && number < 2 ** 32).toBe(true);

            results.add(number);
        }

        expect(results.size).toEqual(1000);
    });

    test("rng generates expected values", () => {
        const rngState = {
            serverSeed: "dbd6d6df67ee0e244ca683bae53b8b6c934ef887782f05763709c59d771f0128",
            clientSeed: "test",
            nonce: 0,
            cursor: 0,
        };

        const values = [
            1336459191, 2239285261, 1397762133, 2995069559, 2904721390, 3292405088, 1046890414, 1614341905, 1108355318, 1096465934, 657961542, 3727988761, 3140972713, 2595284046, 1240759150, 2860469608, 3337027243, 3279691908, 1092285907,
        ]; //these values are generated by Stake algo
        const rng = createProvablyFairRng(rngState);
        values.forEach(value => expect(rng.random()).toEqual(value));
    });

    test("rngs cursor iterates correctly", () => {
        const rngState = {
            serverSeed: "server seed",
            clientSeed: "client seed",
            nonce: 0,
        };

        const rng = createProvablyFairRng({...rngState, cursor: 0});
        rng.random();
        rng.random();
        const rng2 = createProvablyFairRng({...rngState, cursor: 2});

        expect(rng.random()).toEqual(rng2.random());
    });
});
