//values taken from https://en.wikipedia.org/wiki/ISO_4217

export const decimals: Record<string, number> = {
    aed: 2,
    all: 2,
    amd: 2,
    ars: 2,
    aud: 2,
    azn: 2,
    bam: 2,
    // bbd: 2, //not supported by rgs
    bdt: 2,
    bgn: 2,
    bnd: 2,
    bob: 2,
    brl: 2,
    // bve: ?, //not supported by rgs
    cad: 2,
    chf: 2,
    clp: 0,
    cny: 2,
    cop: 2,
    crc: 2,
    czk: 2,
    dkk: 2,
    dop: 2,
    // eek: 2, //not supported by rgs
    eur: 2,
    // fjd: 0, //not supported by rgs
    gbp: 2,
    gel: 2,
    ghs: 2,
    gtq: 2,
    // gyd: 2, //not supoprted
    hkd: 2,
    hnl: 2,
    hrk: 2,
    huf: 2,
    idr: 2,
    ils: 2,
    inr: 2,
    isk: 0,
    jpy: 0,
    kes: 2,
    kgs: 2,
    khr: 2,
    krw: 0,
    kzt: 2,
    lak: 2,
    // ltl: 2, //not supported by rgs
    // lvl: 2, //not supported by rgs
    mad: 2,
    mdl: 2,
    mmk: 2,
    mnt: 2,
    mop: 2,
    mxn: 2,
    myr: 2,
    ngn: 2,
    nio: 2,
    nok: 2,
    nzd: 2,
    pab: 2,
    pen: 2,
    php: 2,
    pln: 2,
    pyg: 0,
    ron: 2,
    rsd: 2,
    rub: 2,
    // rup: ?, //not supported by rgs
    sek: 2,
    sgd: 2,
    thb: 2,
    tjs: 2,
    tnd: 3,
    try: 2,
    twd: 2,
    tzs: 2,
    uah: 2,
    ugx: 0,
    usd: 2,
    uyu: 2,
    // vdo: 0, //not supported by rgs
    // veb: 2, //not supported by rgs
    vnd: 0,
    xaf: 0,
    xcd: 2,
    // xfn: ?, //not supported by rgs
    // xgc: ?,
    xof: 0,
    // xsc: ?,
    // xxx: 0, //not supported by rgs
    zar: 2,
    zmw: 2,
};
