import {MigrationInterface, QueryRunner} from "typeorm";
import {Table} from "typeorm/schema-builder/table/Table";
import {CurrencyFeed} from "../model/CurrencyFeed";

const currencyLayerCurrencies = [
    "amd",
    "kzt",
    "krw",
    "clp",
    "idr",
    "vnd",
    "eur",
    "gbp",
    "usd",
    "chf",
    "cad",
    "sgd",
    "aud",
    "bgn",
    "nzd",
    "azn",
    "ils",
    "brl",
    "pln",
    "dkk",
    "gel",
    "myr",
    "pen",
    "ron",
    "mnt",
    "hkd",
    "nok",
    "sek",
    "try",
    "cny",
    "zar",
    "czk",
    "mxn",
    "ars",
    "twd",
    "uah",
    "php",
    "thb",
    "rub",
    "inr",
    "jpy",
    "huf",
    "pkr",
    "bdt",
    "cdf",
    "mkd",
    "mdl",
    "mvr",
    "cop",
    "crc",
    "bif",
    "xof",
    "xaf",
    "zmw",
    "mzn",
    "aoa",
    "mmk",
    "lkr",
    "tnd",
    "ngn",
    "aed",
    "afn",
    "all",
    "ang",
    "bam",
    "bhd",
    "bnd",
    "bob",
    "bwp",
    "byn",
    "bzd",
    "cup",
    "dop",
    "dzd",
    "egp",
    "etb",
    "ghs",
    "gmd",
    "gnf",
    "gtq",
    "hnl",
    "htg",
    "iqd",
    "irr",
    "isk",
    "jmd",
    "jod",
    "kes",
    "kgs",
    "khr",
    "kwd",
    "lak",
    "lbp",
    "lrd",
    "lsl",
    "mad",
    "mga",
    "mop",
    "mur",
    "mwk",
    "nad",
    "nio",
    "npr",
    "omr",
    "pab",
    "pyg",
    "qar",
    "rsd",
    "rwf",
    "sar",
    "scr",
    "sdg",
    "srd",
    "szl",
    "tjs",
    "tmt",
    "ttd",
    "tzs",
    "ugx",
    "uyu",
    "uzs",
    "xcd",
    "yer",
    "ves",
    "lyd",
];
const ecbCurrencies = ["usd", "jpy", "bgn", "czk", "dkk", "gbp", "huf", "pln", "ron", "sek", "chf", "isk", "nok", "try", "aud", "brl", "cad", "cny", "hkd", "idr", "ils", "inr", "krw", "mxn", "myr", "nzd", "php", "sgd", "thb", "zar"];
const cryptoCurrencies = ["btc", "eth", "ltc", "doge", "trx", "xrp", "bch", "ppc", "usdt", "xrp", "bnb", "ada", "trx", "usdc", "ton"];

export class CreateCurrencyFeed1709131433000 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.createTable(
            new Table({
                name: queryRunner.connection.options.entityPrefix + "currency_feed",
                columns: [
                    {name: "feed", type: "varchar", isPrimary: true},
                    {name: "enabled", type: "boolean"},
                    {name: "currencies", type: "jsonb"},
                    {name: "config", type: "jsonb"},
                ],
            }),
            true,
        );

        await queryRunner.manager.insert(CurrencyFeed, {feed: "currencyLayer", enabled: false, currencies: currencyLayerCurrencies, config: {secretKey: "enter-your-secret-key"} as any});
        await queryRunner.manager.insert(CurrencyFeed, {feed: "ecb", enabled: true, currencies: ecbCurrencies, config: {}});
        await queryRunner.manager.insert(CurrencyFeed, {feed: "coinAPI", enabled: false, currencies: cryptoCurrencies, config: {secretKey: "enter-your-secret-key"} as any});
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.dropTable(queryRunner.connection.options.entityPrefix + "currency_feed", true);
    }
}
