export interface IPermission {
    name: string;
    description: string;
}

export const permissions: IPermission[] = [
    {name: "graphiql", description: "Graphical GraphQL interface"},
    {name: "verifier", description: "Runs automated wallet and game API verification"},
    {name: "wallets", description: "List wallets"},
    {name: "games", description: "List games"},
    {name: "rgss", description: "List RGS's"},
    {name: "accounts", description: "List Back Office accounts"},
    {name: "players", description: "List players"},
    {name: "sessions", description: "List sessions"},
    {name: "campaigns", description: "List campaigns"},
    {name: "manageCampaigns", description: "Manage campaigns"},
    {name: "manageThemes", description: "Manage campaign themes"},
    {name: "transactions", description: "List transactions"},
    {name: "gameWin", description: "List Game Win report"},
    {name: "currencyExchange", description: "List currency exchange rates"},
    {name: "currencyAliases", description: "List currency aliases"},
    {name: "settings", description: "List currency aliases"},
    {name: "fixedCurrencyRates", description: "List fixed currency rates"},
    {name: "manageAccounts", description: "Manage Back Office accounts"},
    {name: "manageCurrencies", description: "Manage currency aliases, fixed rates and feeds"},
    {name: "manageRgss", description: "Manage RGS's"},
    {name: "manageWallets", description: "Manage wallet"},
    {name: "closeTransaction", description: "Force closing of transactions"},
    {name: "manageSettings", description: "Manage setting"},
    {name: "managePlayers", description: "Manage players"},
    {name: "endSession", description: "End session"},
    {name: "regenerateGameWin", description: "Regenerate aggregated game winnings"},
    {name: "auditLogs", description: "Show audit logs"},
    {name: "availableBets", description: "List available game bets"},
    {name: "criticalFiles", description: "List critical files"},
    {name: "manageCriticalFiles", description: "Manage critical files"},
    {name: "manageGames", description: "Manage games"},
    {name: "rtpMonitoring", description: "List RTP Monitoring"},
    {name: "manageRtpMonitoring", description: "Manage RTP Monitoring"},
    {name: "rooms", description: "List rooms"},
    {name: "manageRooms", description: "Manage Rooms"},
    {name: "gameplay", description: "List game play related data"},
    {name: "reportSender", description: "Report sender"},
    {name: "manageReportSender", description: "Manage report sender"},
    {name: "reportExclusion", description: "Report exclusions"},
    {name: "manageReportExclusion", description: "Manage report exclusions"},
];
